{{- if eq .Values.omType "cache" }}
  {{- if or (eq .Values.persistentType "None" ) (eq .Values.persistentType "sharedAll" ) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bediscoverynode.fullname" . }}
spec:
  replicas: {{ .Values.discoverynode.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "bediscoverynode.fullname" . }}
  serviceName: {{ include "discoveryservice.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "bediscoverynode.fullname" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.discoverynode.imagePullSecrets }}    #if required
      containers:
      - name: {{ .Values.discoverynode.containers.name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: {{ .Values.discoverynode.containers.env.PU1name }}
          value: {{ .Values.discoverynode.containers.env.PU1value }}
  {{- end }}
{{- end }}
