#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#
{{- if or (eq .Values.cmType "as2" ) (eq .Values.cmType "ftl" ) (eq .Values.cmType "unclustered" ) (eq .Values.cmType "ignite" ) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "beinferenceagent.fullname" . }}"
spec:
  replicas: {{ .Values.inferencenode.replicaCount }}
  selector:
    matchLabels:
      name: "{{ include "beinferenceagent.fullname" . }}"
  serviceName: "{{ include "beservice.fullname" . }}"
  template:
    metadata:
      labels:
        name: {{ include "beinferenceagent.fullname" . }}
    spec:
      imagePullSecrets:
        {{- if .Values.imagepullsecret }}
        - name: {{ .Values.imagepullsecret }}
        {{- else  }}
        - name: {{ include "beimagepullsecret.fullname" . }}
        {{- end  }}
      containers:
      - name: {{ .Values.inferencenode.containers.name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: PU
          value: default
        {{- range $key,$val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val }}
        {{- end}}
        - name: ENGINE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name          
{{ include "discovery_url" . | trim | indent 8 }}
{{ include "healthcheck" . | trim | indent 8 }}
{{ include "influx-grafana.data" . | trim | indent 8 }}        
{{ include "store.configMap" . | trim |  indent 8 }}
{{ include "sharednothing.volumeMount" . | trim | indent 8 }}
{{ include "sharednothing.volumeClaim" . }}
{{- end }}
