#
# Copyright (c) 2019-2020. TIBCO Software Inc.
# This file is subject to the license terms contained in the license file that is distributed with this file.
#
{{- if or (eq .Values.cmType "AS2" ) (eq .Values.cmType "FTL" ) (eq .Values.cmType "unclustered" ) (eq .Values.cmType "IGNITE" ) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "jmxservice.fullname" . }}
spec:
  ports:
    - port: {{ .Values.jmxservice.ports.port }}
      protocol: TCP
  selector:
    name: {{ include "beinferenceagent.fullname" . }}
  type: {{ .Values.jmxservice.type }}
{{- end }}