#Persistent volume claim for security
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: security-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  volumeName: security-pv
---

#Persistent volume claim for shared
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  volumeName: shared-pv
---

#Persistent volume claim for webstudio
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webstudio-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  volumeName: webstudio-pv
---

#Persistent volume claim for notify
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notify-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  volumeName: notify-pv
---
